// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.Misc.AddAttachments;
using StirlingPdf.Api.V1.Misc.AddImage;
using StirlingPdf.Api.V1.Misc.AddPageNumbers;
using StirlingPdf.Api.V1.Misc.AddStamp;
using StirlingPdf.Api.V1.Misc.AutoRename;
using StirlingPdf.Api.V1.Misc.AutoSplitPdf;
using StirlingPdf.Api.V1.Misc.CompressPdf;
using StirlingPdf.Api.V1.Misc.DecompressPdf;
using StirlingPdf.Api.V1.Misc.ExtractImageScans;
using StirlingPdf.Api.V1.Misc.ExtractImages;
using StirlingPdf.Api.V1.Misc.Flatten;
using StirlingPdf.Api.V1.Misc.OcrPdf;
using StirlingPdf.Api.V1.Misc.RemoveBlanks;
using StirlingPdf.Api.V1.Misc.Repair;
using StirlingPdf.Api.V1.Misc.ReplaceInvertPdf;
using StirlingPdf.Api.V1.Misc.ScannerEffect;
using StirlingPdf.Api.V1.Misc.ShowJavascript;
using StirlingPdf.Api.V1.Misc.UnlockPdfForms;
using StirlingPdf.Api.V1.Misc.UpdateMetadata;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.Misc
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\misc
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MiscRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addAttachments property</summary>
        public global::StirlingPdf.Api.V1.Misc.AddAttachments.AddAttachmentsRequestBuilder AddAttachments
        {
            get => new global::StirlingPdf.Api.V1.Misc.AddAttachments.AddAttachmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addImage property</summary>
        public global::StirlingPdf.Api.V1.Misc.AddImage.AddImageRequestBuilder AddImage
        {
            get => new global::StirlingPdf.Api.V1.Misc.AddImage.AddImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addPageNumbers property</summary>
        public global::StirlingPdf.Api.V1.Misc.AddPageNumbers.AddPageNumbersRequestBuilder AddPageNumbers
        {
            get => new global::StirlingPdf.Api.V1.Misc.AddPageNumbers.AddPageNumbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addStamp property</summary>
        public global::StirlingPdf.Api.V1.Misc.AddStamp.AddStampRequestBuilder AddStamp
        {
            get => new global::StirlingPdf.Api.V1.Misc.AddStamp.AddStampRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The autoRename property</summary>
        public global::StirlingPdf.Api.V1.Misc.AutoRename.AutoRenameRequestBuilder AutoRename
        {
            get => new global::StirlingPdf.Api.V1.Misc.AutoRename.AutoRenameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The autoSplitPdf property</summary>
        public global::StirlingPdf.Api.V1.Misc.AutoSplitPdf.AutoSplitPdfRequestBuilder AutoSplitPdf
        {
            get => new global::StirlingPdf.Api.V1.Misc.AutoSplitPdf.AutoSplitPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compressPdf property</summary>
        public global::StirlingPdf.Api.V1.Misc.CompressPdf.CompressPdfRequestBuilder CompressPdf
        {
            get => new global::StirlingPdf.Api.V1.Misc.CompressPdf.CompressPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The decompressPdf property</summary>
        public global::StirlingPdf.Api.V1.Misc.DecompressPdf.DecompressPdfRequestBuilder DecompressPdf
        {
            get => new global::StirlingPdf.Api.V1.Misc.DecompressPdf.DecompressPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The extractImages property</summary>
        public global::StirlingPdf.Api.V1.Misc.ExtractImages.ExtractImagesRequestBuilder ExtractImages
        {
            get => new global::StirlingPdf.Api.V1.Misc.ExtractImages.ExtractImagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The extractImageScans property</summary>
        public global::StirlingPdf.Api.V1.Misc.ExtractImageScans.ExtractImageScansRequestBuilder ExtractImageScans
        {
            get => new global::StirlingPdf.Api.V1.Misc.ExtractImageScans.ExtractImageScansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The flatten property</summary>
        public global::StirlingPdf.Api.V1.Misc.Flatten.FlattenRequestBuilder Flatten
        {
            get => new global::StirlingPdf.Api.V1.Misc.Flatten.FlattenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ocrPdf property</summary>
        public global::StirlingPdf.Api.V1.Misc.OcrPdf.OcrPdfRequestBuilder OcrPdf
        {
            get => new global::StirlingPdf.Api.V1.Misc.OcrPdf.OcrPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeBlanks property</summary>
        public global::StirlingPdf.Api.V1.Misc.RemoveBlanks.RemoveBlanksRequestBuilder RemoveBlanks
        {
            get => new global::StirlingPdf.Api.V1.Misc.RemoveBlanks.RemoveBlanksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repair property</summary>
        public global::StirlingPdf.Api.V1.Misc.Repair.RepairRequestBuilder Repair
        {
            get => new global::StirlingPdf.Api.V1.Misc.Repair.RepairRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replaceInvertPdf property</summary>
        public global::StirlingPdf.Api.V1.Misc.ReplaceInvertPdf.ReplaceInvertPdfRequestBuilder ReplaceInvertPdf
        {
            get => new global::StirlingPdf.Api.V1.Misc.ReplaceInvertPdf.ReplaceInvertPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scannerEffect property</summary>
        public global::StirlingPdf.Api.V1.Misc.ScannerEffect.ScannerEffectRequestBuilder ScannerEffect
        {
            get => new global::StirlingPdf.Api.V1.Misc.ScannerEffect.ScannerEffectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The showJavascript property</summary>
        public global::StirlingPdf.Api.V1.Misc.ShowJavascript.ShowJavascriptRequestBuilder ShowJavascript
        {
            get => new global::StirlingPdf.Api.V1.Misc.ShowJavascript.ShowJavascriptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unlockPdfForms property</summary>
        public global::StirlingPdf.Api.V1.Misc.UnlockPdfForms.UnlockPdfFormsRequestBuilder UnlockPdfForms
        {
            get => new global::StirlingPdf.Api.V1.Misc.UnlockPdfForms.UnlockPdfFormsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updateMetadata property</summary>
        public global::StirlingPdf.Api.V1.Misc.UpdateMetadata.UpdateMetadataRequestBuilder UpdateMetadata
        {
            get => new global::StirlingPdf.Api.V1.Misc.UpdateMetadata.UpdateMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Misc.MiscRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MiscRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/misc", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Misc.MiscRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MiscRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/misc", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
