// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Security.CertSign
{
    /// <summary>The type of the digital certificate</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SignPDFWithCertRequestPostRequestBody
    {
        [EnumMember(Value = "PEM")]
        #pragma warning disable CS1591
        PEM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PKCS12")]
        #pragma warning disable CS1591
        PKCS12,
        #pragma warning restore CS1591
        [EnumMember(Value = "JKS")]
        #pragma warning disable CS1591
        JKS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SERVER")]
        #pragma warning disable CS1591
        SERVER,
        #pragma warning restore CS1591
    }
}
