// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf.Img
{
    /// <summary>The output image format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConvertToImageRequestPostRequestBody
    {
        [EnumMember(Value = "png")]
        #pragma warning disable CS1591
        Png,
        #pragma warning restore CS1591
        [EnumMember(Value = "jpeg")]
        #pragma warning disable CS1591
        Jpeg,
        #pragma warning restore CS1591
        [EnumMember(Value = "jpg")]
        #pragma warning disable CS1591
        Jpg,
        #pragma warning restore CS1591
        [EnumMember(Value = "gif")]
        #pragma warning disable CS1591
        Gif,
        #pragma warning restore CS1591
        [EnumMember(Value = "webp")]
        #pragma warning disable CS1591
        Webp,
        #pragma warning restore CS1591
    }
}
