// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.CsvEscaped;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Html;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Img;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Markdown;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Pdfa;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Presentation;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Text;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.Word;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf.XmlEscaped;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\convert\pdf
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PdfRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The csv property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.CsvEscaped.CsvRequestBuilder Csv
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.CsvEscaped.CsvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The html property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Html.HtmlRequestBuilder Html
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Html.HtmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The img property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Img.ImgRequestBuilder Img
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Img.ImgRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The markdown property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Markdown.MarkdownRequestBuilder Markdown
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Markdown.MarkdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pdfa property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Pdfa.PdfaRequestBuilder Pdfa
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Pdfa.PdfaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presentation property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Presentation.PresentationRequestBuilder Presentation
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Presentation.PresentationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The text property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Text.TextRequestBuilder Text
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Text.TextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The word property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Word.WordRequestBuilder Word
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.Word.WordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The xml property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.XmlEscaped.XmlRequestBuilder Xml
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.XmlEscaped.XmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.PdfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PdfRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert/pdf", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.PdfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PdfRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert/pdf", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
