// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.General.OverlayPdfs
{
    /// <summary>The mode of overlaying: &apos;SequentialOverlay&apos; for sequential application, &apos;InterleavedOverlay&apos; for round-robin application, &apos;FixedRepeatOverlay&apos; for fixed repetition based on provided counts</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OverlayPdfsRequestPostRequestBody
    {
        [EnumMember(Value = "SequentialOverlay")]
        #pragma warning disable CS1591
        SequentialOverlay,
        #pragma warning restore CS1591
        [EnumMember(Value = "InterleavedOverlay")]
        #pragma warning disable CS1591
        InterleavedOverlay,
        #pragma warning restore CS1591
        [EnumMember(Value = "FixedRepeatOverlay")]
        #pragma warning disable CS1591
        FixedRepeatOverlay,
        #pragma warning restore CS1591
    }
}
