// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.Analysis.AnnotationInfo;
using StirlingPdf.Api.V1.Analysis.BasicInfo;
using StirlingPdf.Api.V1.Analysis.DocumentProperties;
using StirlingPdf.Api.V1.Analysis.FontInfo;
using StirlingPdf.Api.V1.Analysis.FormFields;
using StirlingPdf.Api.V1.Analysis.PageCount;
using StirlingPdf.Api.V1.Analysis.PageDimensions;
using StirlingPdf.Api.V1.Analysis.SecurityInfo;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.Analysis
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\analysis
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnalysisRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The annotationInfo property</summary>
        public global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder AnnotationInfo
        {
            get => new global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The basicInfo property</summary>
        public global::StirlingPdf.Api.V1.Analysis.BasicInfo.BasicInfoRequestBuilder BasicInfo
        {
            get => new global::StirlingPdf.Api.V1.Analysis.BasicInfo.BasicInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The documentProperties property</summary>
        public global::StirlingPdf.Api.V1.Analysis.DocumentProperties.DocumentPropertiesRequestBuilder DocumentProperties
        {
            get => new global::StirlingPdf.Api.V1.Analysis.DocumentProperties.DocumentPropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fontInfo property</summary>
        public global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoRequestBuilder FontInfo
        {
            get => new global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The formFields property</summary>
        public global::StirlingPdf.Api.V1.Analysis.FormFields.FormFieldsRequestBuilder FormFields
        {
            get => new global::StirlingPdf.Api.V1.Analysis.FormFields.FormFieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pageCount property</summary>
        public global::StirlingPdf.Api.V1.Analysis.PageCount.PageCountRequestBuilder PageCount
        {
            get => new global::StirlingPdf.Api.V1.Analysis.PageCount.PageCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pageDimensions property</summary>
        public global::StirlingPdf.Api.V1.Analysis.PageDimensions.PageDimensionsRequestBuilder PageDimensions
        {
            get => new global::StirlingPdf.Api.V1.Analysis.PageDimensions.PageDimensionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The securityInfo property</summary>
        public global::StirlingPdf.Api.V1.Analysis.SecurityInfo.SecurityInfoRequestBuilder SecurityInfo
        {
            get => new global::StirlingPdf.Api.V1.Analysis.SecurityInfo.SecurityInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Analysis.AnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalysisRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/analysis", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Analysis.AnalysisRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalysisRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/analysis", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
