// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.General.MergePdfs
{
    /// <summary>The type of sorting to be applied on the input files before merging.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MergePdfsRequestPostRequestBody
    {
        [EnumMember(Value = "orderProvided")]
        #pragma warning disable CS1591
        OrderProvided,
        #pragma warning restore CS1591
        [EnumMember(Value = "byFileName")]
        #pragma warning disable CS1591
        ByFileName,
        #pragma warning restore CS1591
        [EnumMember(Value = "byDateModified")]
        #pragma warning disable CS1591
        ByDateModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "byDateCreated")]
        #pragma warning disable CS1591
        ByDateCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "byPDFTitle")]
        #pragma warning disable CS1591
        ByPDFTitle,
        #pragma warning restore CS1591
    }
}
