// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Misc.ReplaceInvertPdf
{
    /// <summary>Replace and Invert color options of a pdf.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReplaceAndInvertColorRequestPostRequestBody
    {
        [EnumMember(Value = "HIGH_CONTRAST_COLOR")]
        #pragma warning disable CS1591
        HIGH_CONTRAST_COLOR,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_COLOR")]
        #pragma warning disable CS1591
        CUSTOM_COLOR,
        #pragma warning restore CS1591
        [EnumMember(Value = "FULL_INVERSION")]
        #pragma warning disable CS1591
        FULL_INVERSION,
        #pragma warning restore CS1591
    }
}
