// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.ConvertNamespace.Url.Pdf;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Url
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\convert\url
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UrlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pdf property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Url.Pdf.PdfRequestBuilder Pdf
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Url.Pdf.PdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.Url.UrlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UrlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert/url", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.Url.UrlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UrlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert/url", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
