// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf.Text
{
    /// <summary>The output Text or RTF format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PdfToTextOrRTFRequestPostRequestBody
    {
        [EnumMember(Value = "rtf")]
        #pragma warning disable CS1591
        Rtf,
        #pragma warning restore CS1591
        [EnumMember(Value = "txt")]
        #pragma warning disable CS1591
        Txt,
        #pragma warning restore CS1591
    }
}
