// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.ConvertNamespace.Eml;
using StirlingPdf.Api.V1.ConvertNamespace.FileNamespace;
using StirlingPdf.Api.V1.ConvertNamespace.Html;
using StirlingPdf.Api.V1.ConvertNamespace.Img;
using StirlingPdf.Api.V1.ConvertNamespace.Markdown;
using StirlingPdf.Api.V1.ConvertNamespace.Pdf;
using StirlingPdf.Api.V1.ConvertNamespace.Url;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\convert
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConvertRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The eml property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Eml.EmlRequestBuilder Eml
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Eml.EmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The file property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.FileNamespace.FileRequestBuilder File
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The html property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Html.HtmlRequestBuilder Html
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Html.HtmlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The img property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Img.ImgRequestBuilder Img
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Img.ImgRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The markdown property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Markdown.MarkdownRequestBuilder Markdown
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Markdown.MarkdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pdf property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.PdfRequestBuilder Pdf
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Pdf.PdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The url property</summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.Url.UrlRequestBuilder Url
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.Url.UrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/convert", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
