// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Misc.OcrPdf
{
    /// <summary>Specify the OCR type, e.g., &apos;skip-text&apos;, &apos;force-ocr&apos;, or &apos;Normal&apos;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProcessPdfWithOcrRequestPostRequestBody
    {
        [EnumMember(Value = "skip-text")]
        #pragma warning disable CS1591
        SkipText,
        #pragma warning restore CS1591
        [EnumMember(Value = "force-ocr")]
        #pragma warning disable CS1591
        ForceOcr,
        #pragma warning restore CS1591
        [EnumMember(Value = "Normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
    }
}
