// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Misc.ExtractImages
{
    /// <summary>The output image format e.g., &apos;png&apos;, &apos;jpeg&apos;, or &apos;gif&apos;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PDFExtractImagesRequestPostRequestBody
    {
        [EnumMember(Value = "png")]
        #pragma warning disable CS1591
        Png,
        #pragma warning restore CS1591
        [EnumMember(Value = "jpeg")]
        #pragma warning disable CS1591
        Jpeg,
        #pragma warning restore CS1591
        [EnumMember(Value = "gif")]
        #pragma warning disable CS1591
        Gif,
        #pragma warning restore CS1591
    }
}
