// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.General.RearrangePages
{
    /// <summary>The custom mode for page rearrangement. Valid values are:CUSTOM: Uses order defined in PageNums DUPLICATE: Duplicate pages n times (if Page order defined as 4, then duplicates each page 4 times)REVERSE_ORDER: Reverses the order of all pages.DUPLEX_SORT: Sorts pages as if all fronts were scanned then all backs in reverse (1, n, 2, n-1, ...). BOOKLET_SORT: Arranges pages for booklet printing (last, first, second, second last, ...).ODD_EVEN_SPLIT: Splits and arranges pages into odd and even numbered pages.ODD_EVEN_MERGE: Merges pages and organises them alternately into odd and even pages.REMOVE_FIRST: Removes the first page.REMOVE_LAST: Removes the last page.REMOVE_FIRST_AND_LAST: Removes both the first and the last pages.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RearrangePagesRequestPostRequestBody
    {
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        CUSTOM,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVERSE_ORDER")]
        #pragma warning disable CS1591
        REVERSE_ORDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUPLEX_SORT")]
        #pragma warning disable CS1591
        DUPLEX_SORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOOKLET_SORT")]
        #pragma warning disable CS1591
        BOOKLET_SORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIDE_STITCH_BOOKLET_SORT")]
        #pragma warning disable CS1591
        SIDE_STITCH_BOOKLET_SORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ODD_EVEN_SPLIT")]
        #pragma warning disable CS1591
        ODD_EVEN_SPLIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ODD_EVEN_MERGE")]
        #pragma warning disable CS1591
        ODD_EVEN_MERGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMOVE_FIRST")]
        #pragma warning disable CS1591
        REMOVE_FIRST,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMOVE_LAST")]
        #pragma warning disable CS1591
        REMOVE_LAST,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMOVE_FIRST_AND_LAST")]
        #pragma warning disable CS1591
        REMOVE_FIRST_AND_LAST,
        #pragma warning restore CS1591
        [EnumMember(Value = "DUPLICATE")]
        #pragma warning disable CS1591
        DUPLICATE,
        #pragma warning restore CS1591
    }
}
