// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf.Presentation
{
    /// <summary>The output Presentation format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PdfToPresentationRequestPostRequestBody
    {
        [EnumMember(Value = "ppt")]
        #pragma warning disable CS1591
        Ppt,
        #pragma warning restore CS1591
        [EnumMember(Value = "pptx")]
        #pragma warning disable CS1591
        Pptx,
        #pragma warning restore CS1591
        [EnumMember(Value = "odp")]
        #pragma warning disable CS1591
        Odp,
        #pragma warning restore CS1591
    }
}
