// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf.Pdfa
{
    /// <summary>The output PDF/A type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PdfToPdfARequestPostRequestBody
    {
        [EnumMember(Value = "pdfa")]
        #pragma warning disable CS1591
        Pdfa,
        #pragma warning restore CS1591
        [EnumMember(Value = "pdfa-1")]
        #pragma warning disable CS1591
        Pdfa1,
        #pragma warning restore CS1591
    }
}
