// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.Analysis;
using StirlingPdf.Api.V1.ConvertNamespace;
using StirlingPdf.Api.V1.Filter;
using StirlingPdf.Api.V1.General;
using StirlingPdf.Api.V1.Misc;
using StirlingPdf.Api.V1.Pipeline;
using StirlingPdf.Api.V1.Security;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Gets analysis endpoints under <c>/api/v1/analysis</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.Analysis.AnalysisRequestBuilder Analysis
        {
            get => new global::StirlingPdf.Api.V1.Analysis.AnalysisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets conversion endpoints under <c>/api/v1/convert</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.ConvertNamespace.ConvertRequestBuilder Convert
        {
            get => new global::StirlingPdf.Api.V1.ConvertNamespace.ConvertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets filtering endpoints under <c>/api/v1/filter</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.Filter.FilterRequestBuilder Filter
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets general-purpose endpoints under <c>/api/v1/general</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.General.GeneralRequestBuilder General
        {
            get => new global::StirlingPdf.Api.V1.General.GeneralRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets miscellaneous endpoints under <c>/api/v1/misc</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.Misc.MiscRequestBuilder Misc
        {
            get => new global::StirlingPdf.Api.V1.Misc.MiscRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets pipeline endpoints under <c>/api/v1/pipeline</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.Pipeline.PipelineRequestBuilder Pipeline
        {
            get => new global::StirlingPdf.Api.V1.Pipeline.PipelineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Gets security endpoints under <c>/api/v1/security</c>.
        /// </summary>
        public global::StirlingPdf.Api.V1.Security.SecurityRequestBuilder Security
        {
            get => new global::StirlingPdf.Api.V1.Security.SecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
