// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Misc.UpdateMetadata
{
    /// <summary>The trapped status of the document</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetadataRequestPostRequestBody
    {
        [EnumMember(Value = "True")]
        #pragma warning disable CS1591
        True,
        #pragma warning restore CS1591
        [EnumMember(Value = "False")]
        #pragma warning disable CS1591
        False,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
