// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace StirlingPdf.Api.V1.Analysis.AnnotationInfo
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\analysis\annotation-info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnnotationInfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnnotationInfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/analysis/annotation-info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnnotationInfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/analysis/annotation-info", rawUrl)
        {
        }
        /// <summary>
        /// Returns count and types of annotations. Input:PDF Output:JSON Type:SISO
        /// </summary>
        /// <returns>A <see cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo413Error">When receiving a 413 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoPostResponse?> PostAsAnnotationInfoPostResponseAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoPostResponse> PostAsAnnotationInfoPostResponseAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo400Error.CreateFromDiscriminatorValue },
                { "413", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo413Error.CreateFromDiscriminatorValue },
                { "422", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo422Error.CreateFromDiscriminatorValue },
                { "500", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoPostResponse>(requestInfo, global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns count and types of annotations. Input:PDF Output:JSON Type:SISO
        /// </summary>
        /// <returns>A <see cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo413Error">When receiving a 413 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsAnnotationInfoPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoResponse?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoResponse> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo400Error.CreateFromDiscriminatorValue },
                { "413", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo413Error.CreateFromDiscriminatorValue },
                { "422", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo422Error.CreateFromDiscriminatorValue },
                { "500", global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfo500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoResponse>(requestInfo, global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns count and types of annotations. Input:PDF Output:JSON Type:SISO
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::StirlingPdf.Api.V1.Analysis.AnnotationInfo.AnnotationInfoRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AnnotationInfoRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
