// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Img.Pdf
{
    /// <summary>Option to determine how the image will fit onto the page</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConvertToPdfRequestPostRequestBody
    {
        [EnumMember(Value = "fillPage")]
        #pragma warning disable CS1591
        FillPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "fitDocumentToImage")]
        #pragma warning disable CS1591
        FitDocumentToImage,
        #pragma warning restore CS1591
        [EnumMember(Value = "maintainAspectRatio")]
        #pragma warning disable CS1591
        MaintainAspectRatio,
        #pragma warning restore CS1591
    }
}
