// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.General.BookletImposition
{
    /// <summary>The booklet type to create.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookletImpositionRequestPostRequestBody
    {
        [EnumMember(Value = "BOOKLET")]
        #pragma warning disable CS1591
        BOOKLET,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIDE_STITCH_BOOKLET")]
        #pragma warning disable CS1591
        SIDE_STITCH_BOOKLET,
        #pragma warning restore CS1591
    }
}
