// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.General.BookletImposition;
using StirlingPdf.Api.V1.General.Crop;
using StirlingPdf.Api.V1.General.EditTableOfContents;
using StirlingPdf.Api.V1.General.ExtractBookmarks;
using StirlingPdf.Api.V1.General.MergePdfs;
using StirlingPdf.Api.V1.General.MultiPageLayout;
using StirlingPdf.Api.V1.General.OverlayPdfs;
using StirlingPdf.Api.V1.General.PdfToSinglePage;
using StirlingPdf.Api.V1.General.RearrangePages;
using StirlingPdf.Api.V1.General.RemoveImagePdf;
using StirlingPdf.Api.V1.General.RemovePages;
using StirlingPdf.Api.V1.General.RotatePdf;
using StirlingPdf.Api.V1.General.ScalePages;
using StirlingPdf.Api.V1.General.SplitBySizeOrCount;
using StirlingPdf.Api.V1.General.SplitPages;
using StirlingPdf.Api.V1.General.SplitPdfByChapters;
using StirlingPdf.Api.V1.General.SplitPdfBySections;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.General
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\general
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeneralRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bookletImposition property</summary>
        public global::StirlingPdf.Api.V1.General.BookletImposition.BookletImpositionRequestBuilder BookletImposition
        {
            get => new global::StirlingPdf.Api.V1.General.BookletImposition.BookletImpositionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The crop property</summary>
        public global::StirlingPdf.Api.V1.General.Crop.CropRequestBuilder Crop
        {
            get => new global::StirlingPdf.Api.V1.General.Crop.CropRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The editTableOfContents property</summary>
        public global::StirlingPdf.Api.V1.General.EditTableOfContents.EditTableOfContentsRequestBuilder EditTableOfContents
        {
            get => new global::StirlingPdf.Api.V1.General.EditTableOfContents.EditTableOfContentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The extractBookmarks property</summary>
        public global::StirlingPdf.Api.V1.General.ExtractBookmarks.ExtractBookmarksRequestBuilder ExtractBookmarks
        {
            get => new global::StirlingPdf.Api.V1.General.ExtractBookmarks.ExtractBookmarksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mergePdfs property</summary>
        public global::StirlingPdf.Api.V1.General.MergePdfs.MergePdfsRequestBuilder MergePdfs
        {
            get => new global::StirlingPdf.Api.V1.General.MergePdfs.MergePdfsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiPageLayout property</summary>
        public global::StirlingPdf.Api.V1.General.MultiPageLayout.MultiPageLayoutRequestBuilder MultiPageLayout
        {
            get => new global::StirlingPdf.Api.V1.General.MultiPageLayout.MultiPageLayoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The overlayPdfs property</summary>
        public global::StirlingPdf.Api.V1.General.OverlayPdfs.OverlayPdfsRequestBuilder OverlayPdfs
        {
            get => new global::StirlingPdf.Api.V1.General.OverlayPdfs.OverlayPdfsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pdfToSinglePage property</summary>
        public global::StirlingPdf.Api.V1.General.PdfToSinglePage.PdfToSinglePageRequestBuilder PdfToSinglePage
        {
            get => new global::StirlingPdf.Api.V1.General.PdfToSinglePage.PdfToSinglePageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rearrangePages property</summary>
        public global::StirlingPdf.Api.V1.General.RearrangePages.RearrangePagesRequestBuilder RearrangePages
        {
            get => new global::StirlingPdf.Api.V1.General.RearrangePages.RearrangePagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeImagePdf property</summary>
        public global::StirlingPdf.Api.V1.General.RemoveImagePdf.RemoveImagePdfRequestBuilder RemoveImagePdf
        {
            get => new global::StirlingPdf.Api.V1.General.RemoveImagePdf.RemoveImagePdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removePages property</summary>
        public global::StirlingPdf.Api.V1.General.RemovePages.RemovePagesRequestBuilder RemovePages
        {
            get => new global::StirlingPdf.Api.V1.General.RemovePages.RemovePagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rotatePdf property</summary>
        public global::StirlingPdf.Api.V1.General.RotatePdf.RotatePdfRequestBuilder RotatePdf
        {
            get => new global::StirlingPdf.Api.V1.General.RotatePdf.RotatePdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scalePages property</summary>
        public global::StirlingPdf.Api.V1.General.ScalePages.ScalePagesRequestBuilder ScalePages
        {
            get => new global::StirlingPdf.Api.V1.General.ScalePages.ScalePagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The splitBySizeOrCount property</summary>
        public global::StirlingPdf.Api.V1.General.SplitBySizeOrCount.SplitBySizeOrCountRequestBuilder SplitBySizeOrCount
        {
            get => new global::StirlingPdf.Api.V1.General.SplitBySizeOrCount.SplitBySizeOrCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The splitPages property</summary>
        public global::StirlingPdf.Api.V1.General.SplitPages.SplitPagesRequestBuilder SplitPages
        {
            get => new global::StirlingPdf.Api.V1.General.SplitPages.SplitPagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The splitPdfByChapters property</summary>
        public global::StirlingPdf.Api.V1.General.SplitPdfByChapters.SplitPdfByChaptersRequestBuilder SplitPdfByChapters
        {
            get => new global::StirlingPdf.Api.V1.General.SplitPdfByChapters.SplitPdfByChaptersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The splitPdfBySections property</summary>
        public global::StirlingPdf.Api.V1.General.SplitPdfBySections.SplitPdfBySectionsRequestBuilder SplitPdfBySections
        {
            get => new global::StirlingPdf.Api.V1.General.SplitPdfBySections.SplitPdfBySectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.General.GeneralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeneralRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/general", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.General.GeneralRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeneralRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/general", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
