// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.Filter.FilterContainsImage;
using StirlingPdf.Api.V1.Filter.FilterContainsText;
using StirlingPdf.Api.V1.Filter.FilterFileSize;
using StirlingPdf.Api.V1.Filter.FilterPageCount;
using StirlingPdf.Api.V1.Filter.FilterPageRotation;
using StirlingPdf.Api.V1.Filter.FilterPageSize;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.Filter
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\filter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filterContainsImage property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterContainsImage.FilterContainsImageRequestBuilder FilterContainsImage
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterContainsImage.FilterContainsImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterContainsText property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterContainsText.FilterContainsTextRequestBuilder FilterContainsText
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterContainsText.FilterContainsTextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterFileSize property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterFileSize.FilterFileSizeRequestBuilder FilterFileSize
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterFileSize.FilterFileSizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterPageCount property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterPageCount.FilterPageCountRequestBuilder FilterPageCount
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterPageCount.FilterPageCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterPageRotation property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterPageRotation.FilterPageRotationRequestBuilder FilterPageRotation
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterPageRotation.FilterPageRotationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The filterPageSize property</summary>
        public global::StirlingPdf.Api.V1.Filter.FilterPageSize.FilterPageSizeRequestBuilder FilterPageSize
        {
            get => new global::StirlingPdf.Api.V1.Filter.FilterPageSize.FilterPageSizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Filter.FilterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/filter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Filter.FilterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/filter", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
