// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.General.ScalePages
{
    /// <summary>The scale of pages in the output PDF. Acceptable values are A0-A6, LETTER, LEGAL, KEEP.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScalePagesRequestPostRequestBody
    {
        [EnumMember(Value = "A0")]
        #pragma warning disable CS1591
        A0,
        #pragma warning restore CS1591
        [EnumMember(Value = "A1")]
        #pragma warning disable CS1591
        A1,
        #pragma warning restore CS1591
        [EnumMember(Value = "A2")]
        #pragma warning disable CS1591
        A2,
        #pragma warning restore CS1591
        [EnumMember(Value = "A3")]
        #pragma warning disable CS1591
        A3,
        #pragma warning restore CS1591
        [EnumMember(Value = "A4")]
        #pragma warning disable CS1591
        A4,
        #pragma warning restore CS1591
        [EnumMember(Value = "A5")]
        #pragma warning disable CS1591
        A5,
        #pragma warning restore CS1591
        [EnumMember(Value = "A6")]
        #pragma warning disable CS1591
        A6,
        #pragma warning restore CS1591
        [EnumMember(Value = "LETTER")]
        #pragma warning disable CS1591
        LETTER,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL")]
        #pragma warning disable CS1591
        LEGAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "KEEP")]
        #pragma warning disable CS1591
        KEEP,
        #pragma warning restore CS1591
    }
}
