// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Security.AddWatermark
{
    /// <summary>The watermark type (text or image)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddWatermarkRequestPostRequestBody
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
    }
}
