// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Misc.AddPageNumbers
{
    /// <summary>Custom margin: small/medium/large/x-large</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddPageNumbersRequestPostRequestBody
    {
        [EnumMember(Value = "small")]
        #pragma warning disable CS1591
        Small,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "large")]
        #pragma warning disable CS1591
        Large,
        #pragma warning restore CS1591
        [EnumMember(Value = "x-large")]
        #pragma warning disable CS1591
        XLarge,
        #pragma warning restore CS1591
    }
}
