// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StirlingPdf.Api.V1.Analysis.FontInfo
{
    /// <summary>
    /// JSON object containing the requested data or analysis results
    /// </summary>
    [Obsolete("This class is obsolete. Use FontInfoPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FontInfoResponse : global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoPostResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StirlingPdf.Api.V1.Analysis.FontInfo.FontInfoResponse();
        }
    }
}
#pragma warning restore CS0618
