// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using StirlingPdf.Api.V1.Security.AddPassword;
using StirlingPdf.Api.V1.Security.AddWatermark;
using StirlingPdf.Api.V1.Security.AutoRedact;
using StirlingPdf.Api.V1.Security.CertSign;
using StirlingPdf.Api.V1.Security.GetInfoOnPdf;
using StirlingPdf.Api.V1.Security.Redact;
using StirlingPdf.Api.V1.Security.RemoveCertSign;
using StirlingPdf.Api.V1.Security.RemovePassword;
using StirlingPdf.Api.V1.Security.SanitizePdf;
using StirlingPdf.Api.V1.Security.ValidateSignature;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace StirlingPdf.Api.V1.Security
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\security
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecurityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addPassword property</summary>
        public global::StirlingPdf.Api.V1.Security.AddPassword.AddPasswordRequestBuilder AddPassword
        {
            get => new global::StirlingPdf.Api.V1.Security.AddPassword.AddPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addWatermark property</summary>
        public global::StirlingPdf.Api.V1.Security.AddWatermark.AddWatermarkRequestBuilder AddWatermark
        {
            get => new global::StirlingPdf.Api.V1.Security.AddWatermark.AddWatermarkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The autoRedact property</summary>
        public global::StirlingPdf.Api.V1.Security.AutoRedact.AutoRedactRequestBuilder AutoRedact
        {
            get => new global::StirlingPdf.Api.V1.Security.AutoRedact.AutoRedactRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The certSign property</summary>
        public global::StirlingPdf.Api.V1.Security.CertSign.CertSignRequestBuilder CertSign
        {
            get => new global::StirlingPdf.Api.V1.Security.CertSign.CertSignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getInfoOnPdf property</summary>
        public global::StirlingPdf.Api.V1.Security.GetInfoOnPdf.GetInfoOnPdfRequestBuilder GetInfoOnPdf
        {
            get => new global::StirlingPdf.Api.V1.Security.GetInfoOnPdf.GetInfoOnPdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The redact property</summary>
        public global::StirlingPdf.Api.V1.Security.Redact.RedactRequestBuilder Redact
        {
            get => new global::StirlingPdf.Api.V1.Security.Redact.RedactRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeCertSign property</summary>
        public global::StirlingPdf.Api.V1.Security.RemoveCertSign.RemoveCertSignRequestBuilder RemoveCertSign
        {
            get => new global::StirlingPdf.Api.V1.Security.RemoveCertSign.RemoveCertSignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removePassword property</summary>
        public global::StirlingPdf.Api.V1.Security.RemovePassword.RemovePasswordRequestBuilder RemovePassword
        {
            get => new global::StirlingPdf.Api.V1.Security.RemovePassword.RemovePasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sanitizePdf property</summary>
        public global::StirlingPdf.Api.V1.Security.SanitizePdf.SanitizePdfRequestBuilder SanitizePdf
        {
            get => new global::StirlingPdf.Api.V1.Security.SanitizePdf.SanitizePdfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validateSignature property</summary>
        public global::StirlingPdf.Api.V1.Security.ValidateSignature.ValidateSignatureRequestBuilder ValidateSignature
        {
            get => new global::StirlingPdf.Api.V1.Security.ValidateSignature.ValidateSignatureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Security.SecurityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecurityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/security", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StirlingPdf.Api.V1.Security.SecurityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecurityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/security", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
