// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.ConvertNamespace.Pdf.Word
{
    /// <summary>The output Word document format</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PdfToWordRequestPostRequestBody
    {
        [EnumMember(Value = "doc")]
        #pragma warning disable CS1591
        Doc,
        #pragma warning restore CS1591
        [EnumMember(Value = "docx")]
        #pragma warning disable CS1591
        Docx,
        #pragma warning restore CS1591
        [EnumMember(Value = "odt")]
        #pragma warning disable CS1591
        Odt,
        #pragma warning restore CS1591
    }
}
