// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StirlingPdf.Api.V1.Filter.FilterPageCount
{
    /// <summary>The comparison type, accepts Greater, Equal, Less than</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PDFComparisonAndCountPostRequestBody
    {
        [EnumMember(Value = "Greater")]
        #pragma warning disable CS1591
        Greater,
        #pragma warning restore CS1591
        [EnumMember(Value = "Equal")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "Less")]
        #pragma warning disable CS1591
        Less,
        #pragma warning restore CS1591
    }
}
